theme: jekyll-theme-cayman
title: A Gentle Visual Guide to R
description: Welcome to the homepage for the workshop 'A Gentle Visual Guide to R'! being run as part of the Scottish Graduate School for Social Science's 2020 Summer School.
